import re

def sanitize_html(html_content: str) -> str:
    """
    Sanitize HTML content to ensure it's safe to render.
    
    CRITICAL CHANGE:
    We previously used 'bleach', which was escaping JavaScript operators (like <, >)
    inside <script> tags, breaking the generated animations.
    
    Since this content is generated by our AI (which we trust to some degree) 
    and is rendered in a sandboxed <iframe> on the frontend, we will be more lenient.
    
    We mainly want to prevent malicious external script injections if the AI goes rogue.
    """
    
    # 1. Basic check: If it contains suspicious external script sources (not on our allowed list), warn or strip.
    # For now, we allow the AI to generate code. the Frontend iframe sandbox is the primary defense.
    
    # Return content as-is to preserve JS logic (for loops, comparisons, etc.)
    return html_content

